"""Small, authored coding curriculum for local Qwen weight training.

The held-out tasks are excluded from gradient updates. Reference JavaScript is
executed only after authorship review; generated JavaScript is never executed.
"""


TASKS = [
    # JavaScript: complete CommonJS files exporting solve(input).
    dict(id="js-positive-sum", language="javascript", split="train",
         task="Export solve(numbers): sum only finite positive numbers; an empty array returns 0.",
         source="function solve(numbers) { return numbers.reduce((sum, value) => sum + (Number.isFinite(value) && value > 0 ? value : 0), 0); }\nmodule.exports = { solve };\n",
         cases=[[[2, -3, 4, None], 6], [[], 0]]),
    dict(id="js-stable-unique", language="javascript", split="train",
         task="Export solve(values): return first occurrences in original order, comparing values with JavaScript Set semantics.",
         source="function solve(values) { const seen = new Set(); return values.filter(value => { if (seen.has(value)) return false; seen.add(value); return true; }); }\nmodule.exports = { solve };\n",
         cases=[[["a", "b", "a"], ["a", "b"]], [[], []]]),
    dict(id="js-word-counts", language="javascript", split="train",
         task="Export solve(words): return a plain object mapping each string to its occurrence count. Avoid prototype-key collisions.",
         source="function solve(words) { const counts = Object.create(null); for (const word of words) counts[word] = (counts[word] ?? 0) + 1; return counts; }\nmodule.exports = { solve };\n",
         cases=[[["toString", "a", "a"], {"toString": 1, "a": 2}], [[], {}]]),
    dict(id="js-chunk", language="javascript", split="train",
         task="Export solve({items,size}): split items into consecutive arrays of size; reject nonpositive or noninteger size.",
         source="function solve({ items, size }) { if (!Number.isInteger(size) || size < 1) throw new RangeError('size must be positive'); const result = []; for (let i = 0; i < items.length; i += size) result.push(items.slice(i, i + size)); return result; }\nmodule.exports = { solve };\n",
         cases=[[{"items": [1, 2, 3, 4, 5], "size": 2}, [[1, 2], [3, 4], [5]]], [{"items": [], "size": 3}, []]]),
    dict(id="js-sorted-by-score", language="javascript", split="train",
         task="Export solve(rows): return a new array sorted by descending numeric score, breaking ties by ascending name; do not mutate input.",
         source="function solve(rows) { return [...rows].sort((a, b) => b.score - a.score || a.name.localeCompare(b.name)); }\nmodule.exports = { solve };\n",
         cases=[[[{"name": "Z", "score": 2}, {"name": "A", "score": 2}, {"name": "B", "score": 4}], [{"name": "B", "score": 4}, {"name": "A", "score": 2}, {"name": "Z", "score": 2}]], [[], []]]),
    dict(id="js-parse-int", language="javascript", split="train",
         task="Export solve(text): parse a whole signed decimal integer; return null for trailing text or unsafe integers.",
         source="function solve(text) { if (!/^[+-]?\\d+$/.test(text)) return null; const value = Number(text); return Number.isSafeInteger(value) ? value : null; }\nmodule.exports = { solve };\n",
         cases=[["-42", -42], ["12px", None], ["9007199254740993", None]]),
    dict(id="js-merge-records", language="javascript", split="train",
         task="Export solve({base,patch}): return a new shallow merged object; neither input may be mutated.",
         source="function solve({ base, patch }) { return { ...base, ...patch }; }\nmodule.exports = { solve };\n",
         cases=[[{"base": {"a": 1}, "patch": {"a": 2, "b": 3}}, {"a": 2, "b": 3}], [{"base": {}, "patch": {}}, {}]]),
    dict(id="js-balanced-brackets", language="javascript", split="train",
         task="Export solve(text): return whether (), [] and {} brackets are balanced; ignore other characters.",
         source="function solve(text) { const stack = []; const pairs = { ')': '(', ']': '[', '}': '{' }; for (const ch of text) { if ('([{'.includes(ch)) stack.push(ch); else if (Object.hasOwn(pairs, ch) && stack.pop() !== pairs[ch]) return false; } return stack.length === 0; }\nmodule.exports = { solve };\n",
         cases=[["a([{}])", True], ["([)]", False], ["", True]]),
    dict(id="js-merge-sorted", language="javascript", split="heldout",
         task="Export solve({left,right}): merge two ascending numeric arrays into one ascending array, retaining duplicates.",
         source="function solve({ left, right }) { const out = []; let i = 0, j = 0; while (i < left.length && j < right.length) out.push(left[i] <= right[j] ? left[i++] : right[j++]); return out.concat(left.slice(i), right.slice(j)); }\nmodule.exports = { solve };\n",
         cases=[[{"left": [1, 3], "right": [2, 3]}, [1, 2, 3, 3]], [{"left": [], "right": [4]}, [4]]]),
    dict(id="js-longest-run", language="javascript", split="heldout",
         task="Export solve(values): length of the longest consecutive run of equal values; empty input returns 0.",
         source="function solve(values) { let best = 0, run = 0; for (let i = 0; i < values.length; i++) { run = i && values[i] === values[i - 1] ? run + 1 : 1; best = Math.max(best, run); } return best; }\nmodule.exports = { solve };\n",
         cases=[[[1, 1, 2, 2, 2, 1], 3], [[], 0]]),
    # SQL: one SQLite SELECT query over the documented users/orders fixture.
    dict(id="sql-active-users", language="sql", split="train",
         task="Select id and name of active users, ordered by id.",
         source="SELECT id, name FROM users WHERE active = 1 ORDER BY id;",
         expected=[[1, "Ada"], [2, "Ben"], [4, "Dee"]]),
    dict(id="sql-paid-totals", language="sql", split="train",
         task="Select user_id and total amount of paid orders for each user with paid orders, ordered by user_id.",
         source="SELECT user_id, SUM(amount) AS total FROM orders WHERE status = 'paid' GROUP BY user_id ORDER BY user_id;",
         expected=[[1, 25], [2, 7], [3, 30]]),
    dict(id="sql-no-orders", language="sql", split="train",
         task="Select id and name of users with no orders of any status, ordered by id.",
         source="SELECT u.id, u.name FROM users AS u WHERE NOT EXISTS (SELECT 1 FROM orders AS o WHERE o.user_id = u.id) ORDER BY u.id;",
         expected=[[4, "Dee"]]),
    dict(id="sql-order-counts", language="sql", split="train",
         task="Select each user id and the count of all their orders, including zero, ordered by user id.",
         source="SELECT u.id, COUNT(o.id) AS order_count FROM users AS u LEFT JOIN orders AS o ON o.user_id = u.id GROUP BY u.id ORDER BY u.id;",
         expected=[[1, 3], [2, 1], [3, 1], [4, 0]]),
    dict(id="sql-latest-paid", language="sql", split="train",
         task="Select user_id and latest created_at among paid orders, ordered by user_id.",
         source="SELECT user_id, MAX(created_at) AS latest_at FROM orders WHERE status = 'paid' GROUP BY user_id ORDER BY user_id;",
         expected=[[1, "2026-02-01"], [2, "2026-01-03"], [3, "2026-01-04"]]),
    dict(id="sql-average-paid", language="sql", split="train",
         task="Select the average amount of paid orders as average_amount.",
         source="SELECT AVG(amount) AS average_amount FROM orders WHERE status = 'paid';",
         expected=[[15.5]]),
    dict(id="sql-high-value-users", language="sql", split="train",
         task="Select user_id and paid total for users whose paid total is at least 20, ordered by user_id.",
         source="SELECT user_id, SUM(amount) AS paid_total FROM orders WHERE status = 'paid' GROUP BY user_id HAVING SUM(amount) >= 20 ORDER BY user_id;",
         expected=[[1, 25], [3, 30]]),
    dict(id="sql-name-search", language="sql", split="train",
         task="Select id and name where name starts with A, ordered by id.",
         source="SELECT id, name FROM users WHERE name LIKE 'A%' ORDER BY id;",
         expected=[[1, "Ada"]]),
    dict(id="sql-paid-rank", language="sql", split="heldout",
         task="Select user_id and paid total for users with paid orders, ordered by total descending then user_id ascending.",
         source="SELECT user_id, SUM(amount) AS paid_total FROM orders WHERE status = 'paid' GROUP BY user_id ORDER BY paid_total DESC, user_id ASC;",
         expected=[[3, 30], [1, 25], [2, 7]]),
    dict(id="sql-users-with-refunds", language="sql", split="heldout",
         task="Select id and name of users with at least one refunded order, without duplicates, ordered by id.",
         source="SELECT u.id, u.name FROM users AS u WHERE EXISTS (SELECT 1 FROM orders AS o WHERE o.user_id = u.id AND o.status = 'refunded') ORDER BY u.id;",
         expected=[[1, "Ada"]]),
]
